<?php
?>
<div data-role="content" data-iscroll>
    <a href="<?php echo $this->getUrl('mobile_admin/stock')?>" data-role="button"><?php echo $this->__('Stock Manager')?></a>
    <a class="ui-disabled" href="#" data-role="button"><?php echo $this->__('POS')?></a>
    <br/>
    <a href="<?php echo $this->getUrl('mobile_admin/dashboard')?>" data-role="button"><?php echo $this->__('Dashboard')?></a>
    <a href="<?php echo $this->getUrl('mobile_admin/orders')?>" data-role="button"><?php echo $this->__('Orders')?></a>
     <br/>
     <a href="<?php echo $this->getUrl('mobile_admin/index/aboutus')?>" data-role="button"><?php echo $this->__('About Us')?></a>
     <?php /*
    <a href="<?php echo $this->getUrl('mobile_admin/index/test')?>" data-role="button"><?php echo $this->__('Test')?></a>
    */?>
</div>