<div data-role="header" data-position="fixed" >
  	<a data-role="button" data-rel="back" data-icon="home"><?php echo $this->__('ddddBack')?></a>
  	<a href="<?php echo $this->getUrl('adminhtml/dashboard/index')?>" data-icon="home" data-iconpos="notext"	title="Home">Home</a>
	  <h1><?php echo $this->__('Magento Admin')?></h1>
	<a class="ui-btn-right" href="<?php echo $this->getUrl('mobile_admin/index/logout')?>"  data-theme="e"><?php echo $this->__('Log Out') ?></a>
  	<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
</div>