<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="apple-touch-icon" href="<?php echo  $this->getSkinUrl('images/home60.png') ?>" />
<link rel="icon" href="<?php echo $this->getSkinUrl('images/home.png') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/home.png') ?>" type="image/x-icon"/>
<?php echo $this->getCssJsHtml() ?>
