
<div data-role=content data-iscroll>
	<h1>
		<?php echo $this->__('About Us')?>
	</h1>
	<p>You can find more extensions, get information about extensions, and
		rate extensions that you used.</p>
	<p>
		Visit the website: <a href="http://www.snm-portal.com">SNM-Portal.com</a>
	<p>
	<h2>Top Extension from SNM-Portal</h2>
	<ul data-role="listview">
		<li>
			<div class="ui-grid-a">
				<div class="ui-block-a">
					<img style="max-width: 100%"
						src="<?php echo $this->getSkinUrl('images/aboutus/box-pdf-invoice.png')?>" />
				</div>
				<div class="ui-block-b">
					<a
						href="http://www.snm-portal.com/magento-extensions/pdf-print.html">pdfPRINT</a>
					<p></p>
				</div>
			</div>
		</li>
		<li>
			<div class="ui-grid-a">
				<div class="ui-block-a">
					<img style="max-width: 100%"
						src="<?php echo $this->getSkinUrl('images/aboutus/stocklocator.png')?>" />
				</div>
				<div class="ui-block-b">
					<a
						href="http://www.snm-portal.com/magento-extensions/store-locator.html">storeLOCATOR</a>
					<p></p>
				</div>
			</div>
		</li>
		<li>
			<div class="ui-grid-a">
				<div class="ui-block-a">
					<img style="max-width: 100%"
						src="<?php echo $this->getSkinUrl('images/aboutus/cms-editor-professional.png')?>" />
				</div>
				<div class="ui-block-b">
					<a
						href="http://www.snm-portal.com/magento-extensions/cms-content-editor-professional.html">CMS-Content-Editor
						&ndash; Professional</a>
					<p></p>
				</div>
			</div>
		</li>
	</ul>
</div>
