<?php
?>
            <!--
                <block type="adminhtml/store_switcher" name="store_switcher" as="store_switcher" template="store/switcher.phtml">
                    <action method="setUseConfirm"><params>0</params></action>
                </block>
                 -->
	<div data-role="content" data-iscroll>
		<div class="content-primary">
		<ul data-role="listview">
			<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
			<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #122</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
						<li>
				<h3>Order #1232</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
<span class="ui-li-count">12</span>
				<ul data-add-back-btn="true"  data-theme="d">
					<li>
					<h3>Pets</h3>
				<p>All your favorites from aarkvarks to zebras.</p>
						<ul data-add-back-btn="true">
							<li><a href="index.html">Canary</a></li>
							<li><a href="index.html">Cat</a></li>
							<li><a href="index.html">Dog</a></li>
							<li><a href="index.html">Gerbil</a></li>
							<li><a href="index.html">Iguana</a></li>
							<li><a href="index.html">Mouse</a></li>
						</ul>
					</li>
				</ul>
			</li>
			</ul>
	</div>
	</div>

